name: Version Bump on Merge

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Run version bump script
        run: |
          chmod +x ./scripts/bump-version.sh
          ./scripts/bump-version.sh patch my-app
        shell: bash

      - name: Push changes
        run: |
          git push
          git push --tags
