name: Version Bump on Merge

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make bump-version.sh executable
        run: chmod +x ./scripts/bump-version.sh
        shell: bash

      - name: Run version bump script
        run: ./scripts/bump-version.sh
        shell: bash

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "build: bump version to ${{ steps.bump_version.outputs.new_version }} 🚀"
          git tag "${{ steps.bump_version.outputs.new_version }}"
          git push
          git push --tags
